### ISSUE TITLE
Resizable undocked panels

### ISSUE THREAD

**Issue by andrewsantarin** [ticlo/rc-dock#1]
I'm looking at the examples, but right away, I can see one thing's already missing:

Can the undocked components ([`<DockPanel />`](https://github.com/ticlo/rc-dock/blob/master/src/DockPanel.tsx)) be resized yet? I tried to click-drag the handles, but nothing's happening.

**Comment by rinick** [comment]
@andrewsantarin 
hmm, it always works for me. could you try that again? maybe I accidentally committed an unfinished change yesterday?

**Comment by andrewsantarin** [comment]
>could you try that again?
>[...]
>are you looking at the example page or building your own?

@rinick here's a codesandbox: https://codesandbox.io/s/lpm2zzp2y7 using `rc-dock@2.0.1`.

-----
>did you include dist/rc-dock.css?

Yessir, line 5.

**Comment by rinick** [comment]
@andrewsantarin 
sorry, that was my mistake, too many refractories during the weekend.
just fixed it in the above commit.
I will update npm 2.0.2 tomorrow

**Comment by andrewsantarin** [comment]
Sure, @rinick! I'll bump up [my sandbox](https://codesandbox.io/s/lpm2zzp2y7) dependency once you make the update.

**Comment by rinick** [comment]
> Sure, @rinick! I'll bump up [my sandbox](https://codesandbox.io/s/lpm2zzp2y7) dependency once you make the update.

2.0.2 published

**Comment by andrewsantarin** [comment]
Looks to be working on this sandbox, @rinick. Thanks! 👍
