### ISSUE TITLE
New functionality needed, to disable docking of floating Panel.

### ISSUE THREAD

**Issue by settys** [ticlo/rc-dock#10]
Hi,

I need a new functionality in rc-dock, where via a property, I want to be able to disable , the floating panel, from docking back or docking to any other panel.  I don't know if in the current panel, there is anyway I can do this ?

Basically, I need the floating panel to be non-dockable.

We used the Basic Example, on how the floating panel works.  We want the floating panel, tab-9 and tab-10, to be non dockable to anywhere else.

Also, if we would like to disable other panels to dock back into the floating panel.

Kindly help.

**Comment by rinick** [comment]
@settys please check this example
https://ticlo.github.io/rc-dock/examples/disable-dock.html
