### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by rickiezz** [ticlo/rc-dock#108]
Hello,

First of all, really nice library.

A question regarding the animation when a panel is created on middle. Is there a way to turn this off? We doing something which is quite heavy on performance, and it would be better for us if the animation was instant instead of the sliding. Is there a setting that I missed or is that not possible at this moment?

**Comment by rinick** [comment]
I think you can just copy dist/rc-dock.css, and search for "transition" and remove whatever you want
