### ISSUE TITLE
Any theme support?

### ISSUE THREAD

**Issue by nosferatu500** [ticlo/rc-dock#109]
Hi! Do you plan to add theme or dark mode support? I'm using your component with ant.design. It's looks like in next release ant.design will add dynamic theme support to change theme in runtime. Any plans for this in rc-dock?

**Comment by rinick** [comment]
@nosferatu500  in the future I will add less support to customize theme, also having predefined dark and light theme. but it probably won't be dynamic, you will need to load the css

**Comment by nosferatu500** [comment]
Got it. Thanks!

**Comment by rinick** [comment]
resolved in 3.1.0
