### ISSUE TITLE
Vertical tab ?

### ISSUE THREAD

**Issue by velikayikci** [ticlo/rc-dock#110]
Hello,
İs it possible to do this vertical tab?

![image](https://user-images.githubusercontent.com/25893525/133567971-bc8fb162-3756-4773-ae4b-1283ccbe755a.png)

https://rawgit.com/caplin/FlexLayout/demos/demos/v0.5/demo/index.html

**Comment by rinick** [comment]
I think they are minimized tabs.
Right now it's not possible to do that in rc-docks. I might add that in the future

**Comment by velikayikci** [comment]
Thank you @rinick

**Comment by djmisterjon** [comment]
why close ?
