### ISSUE TITLE
Drag behavior broken when DockLayout position not absolute

### ISSUE THREAD

**Issue by thelazydogsback** [ticlo/rc-dock#111]
Hello...
Scenario is that the DockLayout is not the top-most component in the page -- e.g., if you have a navbar on the top of the page, etc.

It seems that to get tab dragging working correctly I need to make the parent DockLayout control to be with the style `position:absolute`.
If the position is `relative`, then when dragging a tab, the window outline never changes vertical position (or it disappears) when dragging. (However, the drop targets still work.)
I can use absolute positioning for the DockLayout, but it just means I need to do some positioning hacks to get the DockLayout in the right place, vs. having it positioned as expected relative to the parent.

thanks

**Comment by rinick** [comment]
could you provide a test case?

**Comment by thelazydogsback** [comment]
Let me know if this helps -- here is the DOM from the body down to my content.
If this isn't enough, I'll try and get something running in a sandbox where I can include rc-dock somewhere.

![image](https://user-images.githubusercontent.com/4603468/133934240-7c4ef465-3f9d-46b8-88b0-5909d797b845.png)

**Comment by rinick** [comment]
I tried display:block and position:relative, seems work for me
could you provide a live example?
