### ISSUE TITLE
Light/dark theming at runtime

### ISSUE THREAD

**Issue by thelazydogsback** [ticlo/rc-dock#112]
How do I change the theme at runtime? -- pass theme to dock-layout from my app context?

**Comment by rinick** [comment]
no, currently it only supports direct css loading
but it's not hard to load a css with react directly, the css link element doesn't have to be inside head
you can just 

```jsx
<div>
  {isDark?<link rel="stylesheet" href="dark.css"/>:<link rel="stylesheet" href="light.css"/>}
  <DockLayout />
</div>
```

**Comment by nosferatu500** [comment]
In my case, I experienced a flickering effect when using the method you provided.

I resolved it by define next in my `main.css` file

```css
@import "rc-dock/dist/rc-dock.css" screen;
@import "rc-dock/dist/rc-dock-dark.css" screen and (prefers-color-scheme: dark);
```

PS: Just leaving this here in case anyone has the same problem.
