### ISSUE TITLE
Tab operation questions

### ISSUE THREAD

**Issue by thelazydogsback** [ticlo/rc-dock#113]
I apologize in advance if I'm missing something regarding rcDock operations - and if there is another more appropriate forum to move questions to, please let me know.

(1) Is there a way to hide / show a tab? (Where 'hidden' here behaves as if the tab were closed (with other tabs filling space, if appropriate), except I can bring it back by un-hiding it, with the contents still in-tact.)

(2) Once I do a newWindow operation and the tab is hosted in another browser window, is there any way to re-dock it?
_Answering own question:_ Just realized that they will re-parent when the stand-alone window is closed.

(3) Is there a way to have 'extra' content per-_tab_?   I'd like to have toolbars that are specific to tabs, but I don't want to use groups because I don't want limit the user as to which tab can be parked where.

(4) It would be great to be able to 'minimize' tabs in some way (0-width with vertical-text tabs docked on right?) 

xiexie

**Comment by rinick** [comment]
1) this feature has an issue, what if you hide a tab, then drag all the other tabs out of this panel?  you will then have a panel with no tab
my suggestion on this one is:  simply remove it from layout, and add a reference to one of the sibling tabs next to it. and  when you need to unhide it, just add it back to its previous sibling tab

3) right now it's impossible, maybe I can add that feature in the future

4) Yes, that's also in the plan, but right now I don't have time to work on that, you can use something similar to my suggestion in 1) and implement it yourself.
