### ISSUE TITLE
Question: How do I resize a floatbox programmatically?

### ISSUE THREAD

**Issue by don1989** [ticlo/rc-dock#115]
Is there a simple way to resize a floatbox programmatically given a tab ID?

I want to be able to change the size from within the component that is inside the tab content. I have a requirement to make a dynamically sized form. So I'd like to be able to just pass an ID to the component and it can then call dockResize(tabId, newWidth, newHeight) or something like that. Is there a way of doing this already?

Thanks!

**Comment by rinick** [comment]
have you tried controlled layout?
