### ISSUE TITLE
Is it possible to drag the tab holding the tab title on/ over the other panel?

### ISSUE THREAD

**Issue by vardhan03** [ticlo/rc-dock#117]
Hi, 
I am not exactly sure if this is done thinking of any design considerations. 
I am facing an issue when dragging the tab holding on title(when title is expanded to the whole width of the tab) on/ over the other panel. But, I can drag the tab holding on title if there is any space to drag and place it. i.e. If the tab feels it fits in the empty space, it allows to do as shown below in the gif.
But, I can do the same when I hold the window (i.e. not the tab title) and drag in any empty space or over the other panel.
The below is the gif :
![Animation](https://user-images.githubusercontent.com/43950124/135604945-54f1ff07-095a-48b1-90ac-65eb8adf4dae.gif)

We cannot observe this issue when tab title doesn't expands to the whole width of the tab. As we generally drag holding the window( necessarily not holding the title). But the issue is persist with the tab titles which aren't flexible(i.e. doesn't expand to the whole width of the tab). 
The below is the gif for small tab titles:
![Animation2](https://user-images.githubusercontent.com/43950124/135606823-a3bb3135-08f6-409c-b98a-b34f389cb4f2.gif)

I felt the behavior is only written for the panels but not the tabs. Is there any reason for this? If not, can we achieve the same behavior of the panels for the tabs too.

**Comment by rinick** [comment]
dragging tab is different from dragging panel, it becomes more clear when you have multiple tabs in the float panel.

2 ideas I might add to  rc-dock to improve this a little bit

1) the full size tab style should only be applied to docked panel, when they are flow, use old style
2) when there is only one tab in the panel, dragging tab should have the same effect like dragging the whole panel

**Comment by rinick** [comment]
resolved in 3.2.0

**Comment by vardhan03** [comment]
Thanks a lot, @rinick, It is working now in the latest version **3.2.0** as we expected.
