### ISSUE TITLE
Is there any way to maximize the tab (not panel) ?

### ISSUE THREAD

**Issue by vardhan03** [ticlo/rc-dock#119]
I am able to close the tab using the context API passing the Tab data as a source and direction as **null** to the dockMove method. Can achieve the same for the panel data.
But, I am unable to do the same to maximize functionality i.e. I am unable to maximize the tab passing the tab data, but I can achieve if I pass Panel Data using context API passing source and direction as **maximize**.

![image](https://user-images.githubusercontent.com/43950124/136785312-cdfed027-55ff-4a2d-b555-ddb53893c3c7.png)
![image](https://user-images.githubusercontent.com/43950124/136785386-3a9c2557-faa4-41dc-90f0-925bb30c1002.png)
It seems, if there it is **Tab Data**, maximize function is calling **maximizeTab** which doesn't do nothing as of now. 

Can I know when can I expect this functionality in place, please?

**Comment by rinick** [comment]
There is no plan to add that feature.
But I think you can simply use some css trick to make it look like there is only one tab in the maximized panel, and make it impossible to switch to other tabs.
