### ISSUE TITLE
How can I get surrounding panel height when docked?

### ISSUE THREAD

**Issue by kang-sw** [ticlo/rc-dock#120]
Is there any way to get panel's height value ? I can get `h` field from `PanelData` when it's floating, but it seems there's no height entry when it's docked (perhaps `DockData`?). And, it seems both floating and docked panels don't make scrolls automatically when they overflow.

![image](https://user-images.githubusercontent.com/32210953/137756147-3a1403f1-c49f-41dd-a78b-d04a02b53e94.png)

![image](https://user-images.githubusercontent.com/32210953/137756992-ef2a0a71-c714-4245-879e-45719591edf6.png)

When I set `max-height` as `100vh`, it makes scrollbar, but it fits to the whole web page, not docked/floating panel element.

![image](https://user-images.githubusercontent.com/32210953/137757248-b4a5e2dc-aea9-4ec3-a87e-6e9a2562cd94.png)

![image](https://user-images.githubusercontent.com/32210953/137757328-ea184331-1e94-453c-b360-c2692e700e9c.png)

How can I get proper scroll operations?

**Comment by rinick** [comment]
I'm not sure what you mean, could you create a test case
