### ISSUE TITLE
Missing props on DockLayout component 

### ISSUE THREAD

**Issue by RianMartins-Movai** [ticlo/rc-dock#124]
Would be great to have a property on DockLayout component to handle changes of active tabs like "**onTabChange**"
This prop would receive a function to be called every tab change.

Additionally would be awesome to have a way to get the active tab of a DockLayout as well.

Many thanks in advance for your consideration.

**Comment by rinick** [comment]
have you tried onLayoutChange?

**Comment by RianMartins-Movai** [comment]
Ok, I was not expecting this kind of information to be in the onLayoutChange event, but I guess this works for me.

Thank you very much.
