### ISSUE TITLE
Possible to dynamically create panel?

### ISSUE THREAD

**Issue by msabramo** [ticlo/rc-dock#126]
Thanks for sharing this excellent library!

I am trying to have a layout where there is only a single panel by default with my main content and then when the user clicks a button, it creates a new panel.

I didn't see any easy way to create panels - it might be possibly if I used a controlled layout, but then I fear I'd lose a lot of the functionality that rc-dock is giving unless I copy a lot of code.

I saw that https://ticlo.github.io/rc-dock/examples/#adv-tab-update shows creating a new tab dynamically and adding it to a panel. I attempted to do the same thing but with the panel having no tabs to start with and that doesn't seem to work.

For example, let's say I make this change to the `adv-tab-update` example:

```diff
diff --git a/example/adv-tab-update.jsx b/example/adv-tab-update.jsx
index 7142829..9aafb43 100644
--- a/example/adv-tab-update.jsx
+++ b/example/adv-tab-update.jsx
@@ -68,7 +68,7 @@ class Demo extends React.Component {
         },
         {
           id: 'my_panel',
-          tabs: [getTab('tab1', 1), getTab('tab2', 2), getTab('tab3', 3), getTab('tab4', 4)],
+          tabs: [],
         },
       ]
     }
```

The `Add Tab` button no longer works if I do that, so it seems that a tab can only be moved to a panel that already has tabs? Is that intentional or a bug?

**Comment by rinick** [comment]
a panel with no tabs will automatically be removed from layout, unless it has panelLock

**Comment by msabramo** [comment]
Ah ok that explains why it's not showing up I guess, thanks! But I don't know if setting `panelLock` helps with my use cases because when there are no tabs, I don't want the panel to take up any space. I tried setting the panel to:

```js
          minWidth: 0,
          minHeight: 0,
          size: 0,
```

but then it never appears.
