### ISSUE TITLE
how to use a custom tab instead of `rc-tabs`

### ISSUE THREAD

**Issue by veeramarni** [ticlo/rc-dock#13]
Can we customize the tabs instead of using the provided [rc-tabs](https://github.com/ticlo/rc-dock/blob/master/src/DockTabs.tsx#L241)?

**Comment by rinick** [comment]
yes, but that means you will need to support the drag drop api provided by rc-dock in your own tab class.
I think it's better to extend rc-tabs and adding features in the TabBar and TabPane instead of replacing it
