### ISSUE TITLE
Overflow menu item key duplicates 

### ISSUE THREAD

**Issue by embeoo** [ticlo/rc-dock#131]
I've got an issue with console warnings for duplicate keys on the overflow menu items.
I can't reproduce in your example (no react?) but in this unrelated sandbox:
https://codesandbox.io/s/mo897nyn6j

1 Change to rc-dock 3.2.4
2 Open devtools/console
2 Click to add one tab
3 Shrink view to get overflow menu button
4 Click overflow menu button to view menu (no need to select anything)
5 Shrink view just some more.

Console will be full of 'Encountered two children with the same key, `tab1`' warnings.

**Comment by rinick** [comment]
I'm not able to reproduce that issue with the above steps :(

**Comment by embeoo** [comment]
And I thought it was so simple and clear..
With shrinking view, I mean making the white browser emulator pane less wide.Attached an image of the end result.
Is there anything about the reproduction you think is more unclear / the reason you can't reproduce?
![Screenshot 2021-11-12 at 14 14 50](https://user-images.githubusercontent.com/53260077/141473796-48590e38-424d-4fa9-a47c-b97119852b8b.png)

**Comment by rinick** [comment]
I see, I can reproduce it now
"Shrink view just some more."
I can only reproduce it when I shrink it to almost nothing, like less than 1 tab's width.

**Comment by rinick** [comment]
It's an issue in rc-tabs lib, I created a ticket there

https://github.com/react-component/tabs/issues/444

**Comment by rinick** [comment]
@embeoo 
if this is a critical issue for you, you can create a PR at rc-tabs. it shouldn't be too hard, 

also, if you can create a test case to prove this issue also exists in ant-design, you can create an issue in ant-design's repo,  which might raise the priority of the PR in rc-tabs.

**Comment by embeoo** [comment]
@rinick Hi, would you consider making a pull request with the change you proposed in the rc-tabs issue above?

**Comment by rinick** [comment]
> @rinick Hi, would you consider making a pull request with the change you proposed in the rc-tabs issue above?

I did. just check the links in the above issue.

If you really need this PR approved ASAP, you can try these
1) create a test case to reproduce it without rc-dock,  maybe with only rc-tabs, or with antd tabs component
2) find a way to increase the code coverage for the PR.

If that's too hard, you can use patch-package to fix that issue locally
https://www.npmjs.com/package/patch-package

**Comment by embeoo** [comment]
My bad, I did not check, thought it stalled after the welcome of a PR.

Thanks, I'll see if I can contribute.
