### ISSUE TITLE
Scrollbar resets if for cached panels on tab change

### ISSUE THREAD

**Issue by adityatoshniwal** [ticlo/rc-dock#136]
Hi,

When a panel has cached: true, and if you go to some other tab and come back the scroll is reset to zero. However, this works completely fine if cached: false.

I've created a sandbox to demo.
https://codesandbox.io/s/rc-dock-scroll-reset-for-cached-0ibt0

Thanks for the good work.

**Comment by rinick** [comment]
rc-dock moves element from one parent to another parent in real dom. And browser will reset the scroll position in that case even the component has exact same size and position

With the current way rc-dock is implemented, that would be really hard to fix

**Comment by adityatoshniwal** [comment]
@rinick It works fine in non-cached mode, did you notice ?

**Comment by rinick** [comment]
I see, I will check if I can fix that.

**Comment by adityatoshniwal** [comment]
Sorry I misunderstood. It works for iframes only.

**Comment by rinick** [comment]
@adityatoshniwal  could you check if it's fixed in 3.2.7

**Comment by adityatoshniwal** [comment]
Hey @rinick,
Unfortunately it doesn't look like working - Check the sandbox here -
https://codesandbox.io/s/rc-dock-scroll-reset-for-cached-3-2-7-9udcm?file=/package.json

**Comment by rinick** [comment]
hmm, it did fix my simple test case. I will check what else can cause that.

**Comment by rinick** [comment]
you have cached=false, means the tab should be completely destroyed when it's not visible. that's why the scroll is reset

if you use cached=true or cached=undefined, it works as expected

**Comment by adityatoshniwal** [comment]
Oh yes, my bad. The sandbox is working. I will try on my actual application.
Thank you !! 😄
