### ISSUE TITLE
Disallow floating boxes to be merged

### ISSUE THREAD

**Issue by adityatoshniwal** [ticlo/rc-dock#138]
Hi,

Currently, the same group floating panels can be merged even if disableDock: true. But I have a requirement where I need to use these floating boxes as individual dialogs.
One solution is to create a different group. But, it would be very helpful if I can create groups dynamically on the fly.

**Comment by adityatoshniwal** [comment]
If you're occupied, I can try to understand the code and raise a PR.

**Comment by rinick** [comment]
what if it's just a new flag says this tab group can not have multiple tabs when used in float panel?

**Comment by adityatoshniwal** [comment]
Yeah, but in my case I can have multiple float panels in the same group.

**Comment by rinick** [comment]
in 3.2.9  you can use floatable = 'singleTab' in your TabGroup

**Comment by adityatoshniwal** [comment]
Woahh !! You're awesome. Thanks a lot. I'll try this.

**Comment by adityatoshniwal** [comment]
It works. Super.
Sorry to trouble you again, but I'm failing to get where exactly the stop icon is coming from when you try to drop.

**Comment by rinick** [comment]
style/dragging.less

```less
.drag-accept-reject {
  &::after {
    content: "🚫";
  }
}
```
