### ISSUE TITLE
Issues when dragging the floating tabs around other windows content 

### ISSUE THREAD

**Issue by vardhan03** [ticlo/rc-dock#141]
Hi @rinick,
When dragging and moving around the tab/tabs on the other windows, the content on the other windows consumes the event and causes the hover/ (Also, I think triggers the mouse up/ mouse down events ...etc.,) and other issues.
The example is below from one of the examples on the RC-dock demo page:

![Animation2](https://user-images.githubusercontent.com/43950124/152116933-519577b8-a91d-4570-8748-e99f28dd3713.gif)

I am using some tables, maps as content on the panels, moving around them causing issues on the tables which hovers the row, pans the map, pops up the marker ...etc.,

I have tried to look into the code, I feel we need to stop propagating the event on drag events. Can you please let me know what might be the issue causing this? Can you let me know any workaround?

**Comment by rinick** [comment]
I use this to prevent dragging event eaten by iframe
```css
body.dock-dragging iframe {
  pointer-events: none;
}
```

you can try that on other element like `.dock-content-holder`
