### ISSUE TITLE
Listeners for changes size of docks and on moving docks

### ISSUE THREAD

**Issue by Likurg2010** [ticlo/rc-dock#15]
Hi, just wanted to ask is it possible to add listeners on 'move' or 'resize' actions on docks? Or, if this possibility is ready now, how can i use it then? Thanks

**Comment by rinick** [comment]
the controlled layout example shows how to get a callback for all layout changes
https://ticlo.github.io/rc-dock/examples/#controlled-layout

does that work for you?

**Comment by Likurg2010** [comment]
Unfortunately, it doesn't fit. Event 'onLayoutChange' is triggering only after finishing of action. I need to listen to action in process - something like triggering actions 'beforeActionStart' and 'afterActionFinished'

**Comment by rinick** [comment]
@Likurg2010 can you use ResizeObserver on the tab content, that might be a better solution since action start and action finished wont cover the size changed caused by things like browser window resize
 
also do you need that for float panels or docked panels?

**Comment by Likurg2010** [comment]
Ok, it sounds like solution) Could you, please, give a little example of using ResizeObserver with tab content?
And about float and docked panels - i need to listen to moving actions of them too. Maybe, i should explain the purpose of the triggering actions during resize or moving of tables. For example, we have some expensive operation (subscription on some data, or few subscriptions on background), which we want to stop during resizing or moving actions, to avoid performance loss. In that case it could be very usefull to trigger some third part activity during panels resize or moving actions.

**Comment by rinick** [comment]
@Likurg2010 
https://github.com/ticlo/ticlo/blob/master/src/ui/component/Virtual.tsx
check line 33 and line 42

**Comment by nooneyet** [comment]
@rinick Your examples of using ResizeObserver are unavailable now... I've tried using ResizeObserver on tab contents and for some reason it doesn't get triggered on height changes, only on width changes.
