### ISSUE TITLE
lock layout to allow only resizing but not dock/undock

### ISSUE THREAD

**Issue by adityatoshniwal** [ticlo/rc-dock#151]
is there any way to achieve this ?

**Comment by rinick** [comment]
maybe you can have a global mouse move event at capture phase, and search for the event target's parent chain, if you find a .dock-bar in any level of parent, kill the event with stopPropagation and preventDefault.

**Comment by adityatoshniwal** [comment]
@rinick I could use the panelLock attribute, but I want it to be temporary and not permanent. For instance if I set panelLock true and saveLayout then it will also be saved.
Nevertheless, I will try your suggestion.

BTW, we had customised wcDocker to allow such locking by providing API method - `lockLayout` with 3 different levels - No lock, prevent docking (allow resizing only) and full lock.
If you're willing to allow this, then may I can spend some time on this.
