### ISSUE TITLE
OnLayoutChange not called for two panels with one tab each

### ISSUE THREAD

**Issue by adiun** [ticlo/rc-dock#158]
This is a common case I think:
   - two panels docked SxS
   - each panel has one tab in it

If a user is in one panel (with the one tab) and then switches to the other panel (with one tab), `onLayoutChange` is not called with the new `currentTabId`. 

This makes some scenarios impossible for clients, for example updating the URL when a tab changes.

**Comment by rinick** [comment]
There is no layout change in that case, doesn't make sense to have a layout change update
I think you should be able to handle that with focus event listener
