### ISSUE TITLE
Single Child Panel

### ISSUE THREAD

**Issue by jcuenod** [ticlo/rc-dock#16]
Is there a way to limit a panel to having one child:
 - prevent dropping of children
 - prevent dropping panel into other tabbar (but allow it to be redocked somewhere else, just not as a tab)
 - no tab bar

Ideally, I'd like to free up the vertical space that is used for the tab bar so maybe it could be moved with a `ctrl-click` anywhere on the panel or something but, alternatively, it could support a handle class that can be dragged.

**Comment by rinick** [comment]
using a unique tab group would prevent other tab from dock into it.
and if you also use `disabledock` in the group it will prevent it from docking into main layout

to hide the tab but still keep the dragging area, you can just use some custom css for the tab group to hide whatever you need

check this example:
https://ticlo.github.io/rc-dock/examples/#panel-style

**Comment by jcuenod** [comment]
Thanks
