### ISSUE TITLE
Prevent drag start on panel extra

### ISSUE THREAD

**Issue by mflament** [ticlo/rc-dock#164]
I am using the panelExtra to add custom actions, and I often have the .doc-bar panel starting drag (small mouse move during click).

Is there a way to disable dragInitiator on panelExtra ?

Thank you.

**Comment by CDoughty08** [comment]
@mflament You can add `drag-ignore` to the panel-extra class list to prevent drag from triggering.

**Comment by mflament** [comment]
Nice, thank you.
