### ISSUE TITLE
Pass header dynamically

### ISSUE THREAD

**Issue by shubhankar1solanki** [ticlo/rc-dock#17]
I need to set-up a functionality wherein I need to add icons next to tab names.
I can't find relevant documentation to pass additional information in the header.
            
![image](https://user-images.githubusercontent.com/29853005/60962116-33d48e00-a32b-11e9-9eff-a8f9e169ada8.png)

Can you please let me know if there is any facility to create the header tab dynamically without modifying `rc-dock` files like through props?

**Comment by rinick** [comment]
it's already in the example
https://ticlo.github.io/rc-dock/examples/#panel-style

**Comment by shubhankar1solanki** [comment]
I want to add the header in such manner.
![Screenshot](https://user-images.githubusercontent.com/29853005/61022699-a9d90380-a3c4-11e9-8756-278e886ab2a8.png)

**Comment by rinick** [comment]
https://ticlo.github.io/rc-dock/examples/#panel-extra
