### ISSUE TITLE
Add new tabs in controlled layout

### ISSUE THREAD

**Issue by Likurg2010** [ticlo/rc-dock#19]
Hi. I'm trying to add new tabs to controlled layout according to your example (https://github.com/ticlo/rc-dock/blob/master/example/panel-extra.jsx), but i have not a big progress here. Are there some moments to know, when i'm adding new tabs in controlled layout, maybe?

**Comment by Likurg2010** [comment]
Sorry, found out what to do already

**Comment by Israel-Kli** [comment]
For anyone who still need it - here is an example for adding tabs to the controlled layout:
https://codesandbox.io/s/rc-dock217-example-8klnz?file=/src/Root.jsx
