### ISSUE TITLE
more well defined types

### ISSUE THREAD

**Issue by veeramarni** [ticlo/rc-dock#2]
I'm looking something like this, but with more type support. Eventually, it would be helpful if someone wants to save the state in the redux as an option. 

```
export const enum GroupOrientation {
    HORIZONTAL,
    VERTICAL,
}

export const enum GroupLocation {
    FIRST,
    LAST,
    NEXT,
    PREVIOUS,
}
export const enum GroupDirection {
    UP,
    DOWN,
    LEFT,
    RIGHT,
}

export const enum GroupsArrangement {

    /**
     * Make the current active group consume the maximum
     * amount of space possible.
     */
    MINIMIZE_OTHERS,

    /**
     * Size all groups evenly.
     */
    EVEN,
}
```

**Comment by rinick** [comment]
I'm working on a controlled layout example.
I think the example will be ready by tomorrow and I will update the version to 2.1.0

**Comment by veeramarni** [comment]
Ok thanks, also looking for `pre-defined` layout 

```
const PRE_DEFINE_LAYOUT = {
    SINGLE: 'single',
    TWO_COLUMNS: 'two-columns',
    THREE_COLUMNS: 'three-columns',
    TWO_ROWS: 'two-rows',
    THREE_ROWS: 'three-rows',
    GRID_2X2: 'grid-2x2',
    TWO_COLUMNS_RIGHT: 'two-columns-right',
    TWO_COLUMNS_BOTTOM: 'two-columns-bottom',
}
```

**Comment by rinick** [comment]
@veeramarni 
fully controlled layout is implemented in 2.1.0
please check this example
https://github.com/ticlo/rc-dock/blob/master/example/controller-layout.jsx

**Comment by rinick** [comment]
> Ok thanks, also looking for `pre-defined` layout
> 
> ```
> const PRE_DEFINE_LAYOUT = {
>     SINGLE: 'single',
> ```

I think have predefined layout type is not enough, you will need to predefine all the tabs in the layout

check this example
https://ticlo.github.io/rc-dock/examples/#save-layout

**Comment by veeramarni** [comment]
I see you would like to have the dependency on the tabs. Can we not create an (empty) layout (without tabs) and eventually we can fill it with tabs and content?

**Comment by rinick** [comment]
> I see you would like to have the dependency on the tabs. Can we not create an (empty) layout (without tabs) and eventually we can fill it with tabs and content?

It doesn't make sense to add tabs later, since user can drag drop and completely change the layout and you lose the location you want to add. It only makes sense during initialization

I think we can define API like this

```
createLayout('single_panel',[tab1, tab2, tab3....])
createLayout('grid_2x2',[tab1, tab2, tab3....])
```

**Comment by veeramarni** [comment]
HI do you have an update on this layout api? Wondering if we save the current state of the layout in the localstorage, we can revive that layout from the data we stored in the localstorage

**Comment by rinick** [comment]
> HI do you have an update on this layout api? Wondering if we save the current state of the layout in the localstorage, we can revive that layout from the data we stored in the localstorage

yes, check the save layout example, it's already has the feature to save layout in memory and load it back
