### ISSUE TITLE
Id start with `+`

### ISSUE THREAD

**Issue by veeramarni** [ticlo/rc-dock#20]
This is not a bug but of curiosity want to know the reason behind using `+` for Id instead of going with `number`?

https://github.com/ticlo/rc-dock/blob/master/src/Algorithm.ts#L352

**Comment by rinick** [comment]
this is only for auto generated id. using + in auto generated id make it easier for people to use numbers in their custom id.

**Comment by veeramarni** [comment]
If I'm defining `id` as number [here](https://github.com/ticlo/rc-dock/blob/master/example/controlled-layout.jsx#L21), it fails with

![image](https://user-images.githubusercontent.com/3382355/61585167-9562dc80-ab23-11e9-9de9-3d9ce7aadf52.png)

**Comment by rinick** [comment]
> If I'm defining `id` as number [here](https://github.com/ticlo/rc-dock/blob/master/example/controlled-layout.jsx#L21), it fails with
> 
> ![image](https://user-images.githubusercontent.com/3382355/61585167-9562dc80-ab23-11e9-9de9-3d9ce7aadf52.png)

I mean you can convert number to string yourself.
But yes, if I allow number id and check the type before using startsWith, it would be more convenient.
