### ISSUE TITLE
When switching tabs quickly, sometimes dock icons are shown and no UI response after that.

### ISSUE THREAD

**Issue by sanoguch** [ticlo/rc-dock#200]
When switching tabs quickly and repeatedly, sometimes dock icons are shown and no UI response after that.
It can be recovered by drag&drop a tab.

![rc-dock-issue](https://user-images.githubusercontent.com/40227819/228139192-7ffee4c9-09ad-4f0b-990d-ec3bb056c537.gif)

I can reproduce this issue with this very simple example.

```
import React from 'react';
import { DockLayout, LayoutData } from 'rc-dock';
import 'rc-dock/dist/rc-dock.css'
import './App.css'

let count = 0;
function newTab() {
    return {
        id: `newtab${++count}`,
        title: `newtab${count}`,
        content: <div>{`Tab${count}`}<button onClick={()=>{alert('button clicked')}}>test</button></div>,
    };
}

const defaultLayout: LayoutData = {
    dockbox: {
        mode: 'horizontal',
        children: [{tabs: [newTab(), newTab(), newTab(), newTab(), newTab()]}]
    }
};

function App() {
    return <DockLayout defaultLayout={defaultLayout}
                       style={{position: 'absolute', left: 10, top: 10, right: 10, bottom: 10,}}/>;
}

export default App;
```

**Comment by vardhan03** [comment]
@sanoguch, Can you please let me know if you have found any work around to this?

**Comment by sanoguch** [comment]
@vardhan03 Do you see this issue? Then can you try fix #203 ?

**Comment by vardhan03** [comment]
Hey, thanks @sanoguch, Where can I actually fix the issue in our code base? I see the issue needs to be fixed in the library. Please correct me if I am wrong. The PR #203 changes are in the files of the library, so I am confused.

**Comment by sanoguch** [comment]
I am not sure what is the right way to commit my changes.
I modified src/DockPanel.tsx and ran the following commands.
```
npm run build-es
npm run build-lib
```
Then, other two files are automatically modified, then I committed them too.

**Comment by sanoguch** [comment]
Workaround in my project is as below.

Clone rc-dock repository.
```
git clone https://github.com/ticlo/rc-dock.git
cd rc-dock
npm install
```
Modify src/DockPanel.tsx as #203.
```
npm run build-es
npm run build-lib
npm pack
```
Then, rc-dock-3.2.17.tgz is created.

In my project, use it instead of rc-dock as below.
```
npm install ./rc-dock-3.2.17.tgz
```

I'd like somebody else to fix this issue officially.

**Comment by vardhan03** [comment]
Got it @sanoguch, we need to fork this repo, add the fix and use it. As you mentioned, it would be better if this issue fixed officially by the author and push the patch version of the library. 
Looks like this issue is out there for everyone I feel.

@rinick, please give an update on this issue asap.
