### ISSUE TITLE
Confirmation before closing the tab

### ISSUE THREAD

**Issue by adityatoshniwal** [ticlo/rc-dock#211]
Hi,

I want to achieve a confirmation dialog before closing. Basically, allowing to cancel the close event.
Is there any way?

Thanks.

**Comment by Israel-Kli** [comment]
@adityatoshniwal You only need to implement the existing `onLayoutChange()` callback with `direction === 'remove'`.

See the example from the docs here:
https://ticlo.github.io/rc-dock/examples/#controlled-layout

**Comment by adityatoshniwal** [comment]
Hi @Israel-Kli,

Its not that straightforward. I need to close the panel based on Yes/No and panels are added dynamically. So can't hardcode.
Anyway, I managed to do that by disabling default close and customizing the title to add own close implmentation.
