### ISSUE TITLE
Dragging entire tab group can clone it

### ISSUE THREAD

**Issue by embeoo** [ticlo/rc-dock#22]
Hi, thought we had caused it, but turned out to be easy to reproduce also in the example.

In https://ticlo.github.io/rc-dock/examples/#drop-mode , drag from the reminder of the bar of the three tabs on the right, to move all of them.

Drop in drop zone above or below itself, staying in the right half.

Both the dragged and dropped groups are now in the layout, with tabs offering double views of the same content. I would expect the result to be no visual change, no matter if the 'move' is carried out or it is deemed meaningless.

This seems to not be an issue when you have more than one bar vertically, or if dropmode isn't edge.

**Comment by embeoo** [comment]
ps. noted that tabLocked, while locking down the tabs, does not lock them if dragged as a group like so.

**Comment by rinick** [comment]
> ps. noted that tabLocked, while locking down the tabs, does not lock them if dragged as a group like so.

tabLocked only lock them inside panel. moving a panel has the same result as moving other panels around it. so I don't see any reason to completely blocking dragging the whole panel.  maybe what you need is just floatable=false ?

**Comment by embeoo** [comment]
Kudos! Overnight correction verified!

About lockedTab, this is a no care for us now, I just investigated if I could hide the corrected problem by disabling group dragging altogether. 

But, as you can drop the group in another bar, I would say that you are moving the locked tabs. But it gets complicated as maybe only some of the tabs are locked...
