### ISSUE TITLE
Some improvements and demands

### ISSUE THREAD

**Issue by agundogdu1** [ticlo/rc-dock#28]
Hi,
The application looks stable and successful in its capabilities.
But we had a similar application before.
Before switching to this application, I wanted to give an opinion on a subject and I think it will make our transition quite easy if we can get a return in a short time. Think of it as a recommendation.
It clusters the windows in the application under three headings with a complex model. Instead, you would consider switching to a data structure such as "items: [{id: 'window1, position: {boxType:' float '....., vs}'}]", which is reduced to a single level. Thus, people who want to use your application but have an existing application do not have to keep data according to your position information.

**Comment by rinick** [comment]
but that would be a huge refactory, and making all the existing application using rc-dock not compatible with newer version.
I think it shouldn't be too hard to create a HOC or wrapper that convert your data structure to/from rc-dock's
