### ISSUE TITLE
common content component for each panel

### ISSUE THREAD

**Issue by veeramarni** [ticlo/rc-dock#3]
Is there a way we can use one common component for a panel with multiple tabs where its state gets updated when the tab changes?

**Comment by rinick** [comment]
https://ticlo.github.io/rc-dock/interfaces/panellock.html#panelextra
if you need it for one locked panel, you can use panelExtra as a state change callback, just return null if you dont want to show extra content

if you need that state change for all panels, you can also define it in panelExtra of the [TabGroup](https://ticlo.github.io/rc-dock/interfaces/tabgroup.html)
