### ISSUE TITLE
BoxData - maxwidth, mawHeight

### ISSUE THREAD

**Issue by richyvie** [ticlo/rc-dock#30]
Hello,

The defaultLayout object foresees the possibility to set a minWidth and a minHeight.
Is there a possibility to set a mawWidth and maxHeight?
If so, could you provide a sample code?

In fact, my left pane should not exceed a certain with, otherwise the layout of my main pane is broke. Or should I define groups? But in that case, I do not see how to set these kind of limitations.

With kind regards,

Richert

**Comment by rinick** [comment]
@richyvie there is one issue about maxwidth. Say you have a v box with 2 panels. Top panel has a min width of 400px. Bottom panel has a Max width of 300px.
