### ISSUE TITLE
Prevent docking to other DockLayout instance

### ISSUE THREAD

**Issue by Letrab** [ticlo/rc-dock#32]
Hi!

First of all, thank you for this library.
I am trying to use it for a specific case in which I could not figure out how to do it:

In the end I want to have:

- Left dock: containing 2 components A & B. These components can be dockable/tabable only in the left dock
- Right dock: containing 2 other components C & D. These components may be dockabel/tabable/floatable only in the right dock

I tried with the groups, but this is only preventing for tabs.
Is there a way for not letting one DockLayout to be containing docks of another DockLayout?

I also tried `disableDock`, but it affects docking as a whole...

**Comment by rinick** [comment]
@Letrab you can use raw Divider to achieve that

btw, your left side 2 component, do you need to drag drop them to reorder? or do you only need them to be resized, but not moving around?

**Comment by Letrab** [comment]
Yes, I used a raw Divider between those 2 panes (left and right). But indeed I want that the 2 components A and B in that left pane to be re-orderable via drag and drop.

So I have now:
DockLayout
Divider
DockLayout

The problem is that it is possible to dock panels from one to the other DockLayout, and I would like to avoid that ;-).

Thanks for your reply!

**Comment by rinick** [comment]
> Yes, I used a raw Divider between those 2 panes (left and right). But indeed I want that the 2 components A and B in that left pane to be re-orderable via drag and drop.
> 
> So I have now:
> DockLayout
> Divider
> DockLayout
> 
> The problem is that it is possible to dock panels from one to the other DockLayout, and I would like to avoid that ;-).
> 
> Thanks for your reply!

yes, this requirement makes sense, I will work on that

**Comment by rinick** [comment]
now DockLayout by default doesn't allow you to drag from one Layout to another.
Also check the divider-box example https://ticlo.github.io/rc-dock/examples/#divider-box
