### ISSUE TITLE
Not work drag and drop rc-dock component in tab of other rc-dock component.

### ISSUE THREAD

**Issue by omarty** [ticlo/rc-dock#35]
Hello. Please tell me, how I can correctly use rc-dock component in tab of other rc-dock component. I find problem, drag and drop of inner rc-dock component not working. If tab of outer rc-dock in floatable mode - working ok. But in "horizontal" or "vertical" mode, images for drag and drop not displayed when I drag tab.

**Comment by rinick** [comment]
are you using a dock layout inside another dock layout?

**Comment by omarty** [comment]
> are you using a dock layout inside another dock layout?

Yes, I tried. But working with problems.

**Comment by rinick** [comment]
could you test with 2.5.2 and see if your issue is resolved?

**Comment by omarty** [comment]
> could you test with 2.5.2 and see if your issue is resolved?

Yes it works. Thank you so much!
