### ISSUE TITLE
Couldn't get dropMode="edge" to work

### ISSUE THREAD

**Issue by andrewsantarin** [ticlo/rc-dock#4]
Used the drop mode example below:

https://github.com/ticlo/rc-dock/blob/21b3af24be62be96dafe6f1affbabd949d0d5742/example/drop-mode.jsx#L1-L51

[I tried to create an example CodeSandbox for it](https://codesandbox.io/s/0mjo76mnz0), but it doesn't work. The `<div className='dock-drop-indicator'>` in the element wouldn't show any changes in size so effectively, drop mode doesn't register into the component. Did I forget to configure it? All I needed is `dropMode="edge"`, right?

**Comment by rinick** [comment]
@andrewsantarin probably the css are not updated after I added dropmode.
I will fix that tomorrow

**Comment by rinick** [comment]
@andrewsantarin
fixed, could you try that again

**Comment by andrewsantarin** [comment]
@rinick 
looks like it's working now, thanks for the fix
