### ISSUE TITLE
problem when right click in multiple windows

### ISSUE THREAD

**Issue by nash12548** [ticlo/rc-dock#42]
hi sorry for my bad English 
very thanks for your good library 
i made a custom contextmenu shown with right-click .
when i use rc-dock and have multiple window (or tab) and do right click on a window this error shown in console but when i close all tabs (or windows) except one of them and do right click error noting shown in console thanks for any help.

**i use this library's :**
material-ui for theme.
react-contexify for contextmenu.
stockcharts for  charting.
rc-dock for multiple windows

**error:**
Uncaught TypeError: Cannot read property 'offsetWidth' of undefined
    at Menu.setMenuPosition (Menu.tsx:162)
    at callCallback (react-dom.development.js:12490)
    at commitUpdateQueue (react-dom.development.js:12511)
    at commitLifeCycles (react-dom.development.js:19858)
    at commitLayoutEffects (react-dom.development.js:22803)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at commitRootImpl (react-dom.development.js:22541)
    at unstable_runWithPriority (scheduler.development.js:653)
3VM79 react_devtools_backend.js:6 The above error occurred in the <Menu> component:
    in Menu (created by MyAwesomeMenu)
    in MyAwesomeMenu (created by CandleStickChartWithDarkTheme)
    in div (created by CandleStickChartWithDarkTheme)
    in CandleStickChartWithDarkTheme (created by fitWidth(CandleStickChartWithDarkTheme))
    in fitWidth(CandleStickChartWithDarkTheme) (created by Root)
    in div (created by Root)
    in div (created by DockTabPane)
    in DockTabPane (created by DockTabs)
    in div (created by TabContent)
    in TabContent (created by Tabs)
    in div (created by Tabs)
    in Tabs (created by DockTabs)
    in DockTabs (created by DockPanel)
    in div (created by DragDropDiv)
    in DragDropDiv (created by DockPanel)
    in DockPanel (created by DockBox)
    in div (created by DockBox)
    in DockBox (created by DockLayout)
    in div (created by DockLayout)
    in DockLayout (created by Root)
    in Root (created by Context.Consumer)
    in Route (created by BaseRouter)
    in Switch (created by BaseRouter)
    in Suspense (created by BaseRouter)
    in div (created by BaseRouter)
    in BaseRouter (created by App)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by ForwardRef(Drawer))
    in div (created by ForwardRef(Drawer))
    in ForwardRef(Drawer) (created by WithStyles(ForwardRef(Drawer)))
    in WithStyles(ForwardRef(Drawer)) (created by MiniDrawer)
    in ThemeProvider (created by MiniDrawer)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (created by MiniDrawer)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (created by MiniDrawer)
    in div (created by MiniDrawer)
    in MiniDrawer (created by App)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by App)
    in App (created by ConnectFunction)
    in ConnectFunction
    in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
r @ VM79 react_devtools_backend.js:6
react-dom.development.js:11102 Uncaught TypeError: Cannot read property 'offsetWidth' of undefined
    at Menu.setMenuPosition (Menu.tsx:162)
    at callCallback (react-dom.development.js:12490)
    at commitUpdateQueue (react-dom.development.js:12511)
    at commitLifeCycles (react-dom.development.js:19858)
    at commitLayoutEffects (react-dom.development.js:22803)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at commitRootImpl (react-dom.development.js:22541)
    at unstable_runWithPriority (scheduler.development.js:653)

**Comment by rinick** [comment]
It seems the error is in the Menu component, not directly from rc-dock 
does this error only happen when you put things in a rc-dock tab? and it works fine when running without rc-dock?

could you make a test case for me so I can take a look?

**Comment by nash12548** [comment]
tnx for replay
it works fine when running without rc-dock without any problem.

**Comment by nash12548** [comment]
i create this codesandbox of problem [](https://codesandbox.io/s/tender-rhodes-kcngx)

**Comment by rinick** [comment]
> i create this codesandbox of problem [link](https://codesandbox.io/s/tender-rhodes-kcngx)

I can easily reproduce this bug without rc-dock,
simply use your  `<Contextmenu />`  twice in any component will show the same error
