### ISSUE TITLE
Feature Request: Enabling users of RC-dock to decide how to render panel contents

### ISSUE THREAD

**Issue by johnjesse** [ticlo/rc-dock#48]
Hey,

So I'd like to use RC-dock with a different tabs component - for styling and accessibility purposes. Looking at it - I think one option would be a render prop e.g. `renderPanelContent` for rendering the panel contents. That could be given the panel data - and the drag-drop listener calls - that are currently given to `DockTabs` and render a component.

There'd still need to be something done for the drop behaviour of the tabs into the tab bar -> right now I think that's done by the `DragDropDiv` inside the `DockTabBar` -> I'm not quite certain how we'd enable that. yet, maybe expose the `DragDropDiv` so it could be used by the `renderPanelContent` prop.

What do you think?
I'm happy to try this out and come up with a proposal
Do you think it could be incorporated into the rc-dock package?

**Comment by rinick** [comment]
yes, as long as it doesn't break existing projects.

maybe you should write a list of rc-dock classes you want to change, and list of classes that you no longer want to use in your project. So I can have a better understanding of your plan.

**Comment by johnjesse** [comment]
So what I'm proposing is that we add something to rc-dock to allow the user to take control of the rendering of the panelData. The obvious difficulty in this is that rc-dock has excellent drag drop behaviour and any user wouldn't want to lose that. So -> I'd want to do some refactoring to make that drag drop behaviour easily re-usable by someone implementing the proposed `renderPanelContents` prop.

The two bits that we'd need are a
1.  `DragDropTabHeader` component - that would be used by the user to wrap their own tab headers
2.  `DragDropPanelHeader` component - that would be used by the user to wrap their own panel header.
3. A context to pass down the relevant handlers to these components -> so it doesn't matter where/if they are rendered by the user, 

So overall I'm proposing
1. Provide a `PanelHeaderDragDropContext` to the children rendered by `DockPanel` -> this would have the current `onDragStart` `onDragEnd` and `onDragMove` handlers on it.

2. Extract a `DragDropPanelHeader` component from the `DockTabBar` component  - this component just takes the `onDragStart` `onDragEnd` and `onDragMove` handlers off the `PanelHeaderDragDropContext` and adds them to a `DragDropDiv` -> as well as passing any props it receives through to the `DragDropDiv`. This component would be made public for anyone rendering the panel contents themselves to use. I'd refactor `DockTabBarRootNode` to use it too, and `DockTabBar` would no longer take the `onDrag...` props.

3. Extracting a  `DragDropTabHeader` from the current TabCache - it would take in some props to get the `tabData` and the `tabHeaderElement`. This component would be made public for anyone implementing renderPanelContents to use. Then refactor `TabCache` to use that component too. This means the user has to provide the `panelData` and a way to get the `headerElement` for this component to work correctly when implementing their own `renderPanelContents` function, which I think is OK.

4. In `DockTabs`, removing the `onPanelDragDrop...` props - as they now get to the panel header rendered by the tabs through context.

5. Add a optional prop to the `DockPanel` called `renderPanelContents` that could be used to render the contents of the panel. This would take the `panelData` as an argument - and the `DockContext` as a second argument - so that the user can remove the tab -> call maximise etc. It might be nice to provide a facade over the `DockContext` so it's not all exposed - on the other hand - the user has more flexibility if the whole context is available

6.  Add the same prop to `DockBox` and `DockLayout` so that it can be internally passed down to the panel from a user who renders the `DockLayout`

7. In `DockPanel` if we have a `renderPanelContents` prop -> call it with the current `panelData`, and the `DockContext` - otherwise, and add a default prop for this - that just takes the `panelData` and renders `<DockTabs panelData={panelData} />`

I'm going to give this a go and see if it works, I think if all the examples still work that would suggest it does - and then I should be able to add an extra example rendering another tab control in there.

There is some specific code in `TabCache` `getDropDirection` which clearly expects the tabHeader to be horizontally aligned -> which may not be true if the user has control over the rendering - but I think that's a later problem to solve. It could probably be solved by adding an `orientation` prop to the `DragDropTabHeader` component.

@rinick - please let me know your thoughts

**Comment by rinick** [comment]
The plan looks promising.
How about tab's caching features? 
right now DockTabPane is calling `getTabCache()` from the context. so the tab's state will remain the same after moved to different parent.
If we are going to skip the TabCache class, the DockTabPane might also need some change so it doesn't rely on props from rc-tabs. Otherwise people will need to re-implement this caching mechanism.

**Comment by johnjesse** [comment]
Ah... ok - I don't think I had twigged what the cache was for until your comment. I see that there are two caches
1. The `DockTabs` has a map of tab `id` to `TabCache` - this appears to be only a cache for the current set of tabs - recreated if that set of tabs is re-mounted e.g. on panel move.
2. The `DockLayout` contains a cache - of all tabs - that is used in `DockTabPane` - that will persist if a tab/panel is moved.

I think you're right, it would be nice to keep the caching behaviour across if the tab is moved to a different parent - I'll think a bit further about that. We'd need to split `DockTabPane` into two probably -> a component that just does the caching across the `DockLayout` that could be re-used by someone writing their own `renderPanelContents` and a component that does the rest of what `DockTabPane` currently does...
