### ISSUE TITLE
How do I find the most recent active panel when the layout state changes?

### ISSUE THREAD

**Issue by andrewsantarin** [ticlo/rc-dock#5]
One reason I've considered [`flexlayout-react`](https://github.com/caplin/FlexLayout) is that it memorizes which panel was last active due to a user action, such as...

- adding a new tab
- moving a tab panel
- rearranging the tabs in a panel
- clicking on a tab to edit an input field
- etc etc...

It allows my team to easily assign new content to the last changed panel, kind of like what users normally do in a desktop environment. Compare this behavior to browsers: 

>when you put hide the browser in the background and open a link from, let's say, a text editor, it automatically opens a new tab right next to your last tab,

Unfortunately, I don't see a solid approach of that here outside of handling `afterPanelLoaded` or calling some object diffing algorithm to tell the difference between the old and new layout state. Here's how I've attempted it: https://codesandbox.io/s/mo897nyn6j. Even then, it's hard to tell which panel was last worked on.

I do have an algorithm to do reverse searching from panel to tab: i.e to find out which panel the tab currently belongs to. I used https://github.com/ticlo/rc-dock/blob/5d6ce97bd4795967473908ba517ecf80749f9dcb/src/Algorithm.ts#L57-L91 as the foundation for it. Unfortunately, that's just finding the panel from a tab. I don't know yet how to tell where other kinds of changes happen.

Algorithm gist for find parent panel of tab: https://gist.github.com/andrewsantarin/6835090e7faa6ef07a6e564328b15f41

Is there any way of working around this for now?

**Comment by andrewsantarin** [comment]
P.S. perhaps diffing the old & new layout states directly is a bad idea; is it wiser to flatten the two layout structures first, then compare them with each other for changes?

**Comment by rinick** [comment]
some action can have a last active tab, like moving tab, adding tab, switching tab in panel.
but there are other action this doesn't make sense, for example, closing a tab (which might also cause the panel to be destroyed)  moving a whole panel with multiple tabs. resize panels.

and another thing is: `clicking on a tab to edit an input field` this wont trigger a layout change.
would that make more sense to use a focus listener in the tab content to monitor that?

**Comment by andrewsantarin** [comment]
> some action can have a last active tab, like moving tab, adding tab, switching tab in panel.

Yeah, I'm looking for this use case. With what we have now, how should I approach this? Through plain JS?


> but there are other action this doesn't make sense, for example, closing a tab (which might also cause the panel to be destroyed) moving a whole panel with multiple tabs. resize panels.

If it doesn't make sense when a whole panel is closed, then I think I can live with that.

Moving a whole panel, though... I believe some kind of `onFocus` handler (like written below) will help me solve my problem, am I correct?


> and another thing is: `clicking on a tab to edit an input field` this wont trigger a layout change.
> would that make more sense to use a focus listener in the tab content to monitor that?

Yeah, actually.

-------

I'm starting to believe that `window.addEventListener('focus')` is roughy the solution to all of these problems while there is no baked-in solution yet. However, I'm still concerned about rerendering only due to the fact that the last active panel is a separate state from the main layout data.

**Comment by rinick** [comment]
@andrewsantarin please check the latest version, onLayoutChange callback now has the currentTabid in second parameter

**Comment by andrewsantarin** [comment]
Sorry, didn't reply soon enough. But yes, I tested it. It's available now ([CodeSandbox example](https://codesandbox.io/s/6wox93onon)). Thank you.
