### ISSUE TITLE
Minimize?

### ISSUE THREAD

**Issue by virus2016** [ticlo/rc-dock#52]
Hi there,

I am not sure if this is possible just now. Can I minimize a tab or set the height of a vertical tab programmatically rather than dragging? 

Many thanks,

**Comment by rinick** [comment]
Hi
you can use the dockMove api on the DockLayout instance
https://ticlo.github.io/rc-dock/classes/docklayout.html#dockmove
direction should be "maximize", it will maximize a panel when it's docked, and restore the panel when it's already maximized

**Comment by kimminbae** [comment]
so, this should not be closed.
I am also curious how the minimize dockMove can be coded.
