### ISSUE TITLE
popout window

### ISSUE THREAD

**Issue by cuthbe** [ticlo/rc-dock#53]
Are there plans to put a browser popout window in for this? So you can pop a dock out from the browser window?

**Comment by rinick** [comment]
there are a lot of issues related that make it almost impossible:

-  any library that relies on global document or window will need to be updated. `document` should be changed to `currentElement.ownerDocument` 
  - global mouseup listener for click outside or drag/drop
  - library that need to add element to document body, like popup tooltip etc
- ResizeObserver can't detect element size change properly in other window

**Comment by rinick** [comment]
since this PR is merged:
https://github.com/react-component/trigger/pull/227

I will work on this task a little bit and see how it goes

**Comment by rinick** [comment]
this is resolved in 3.0.0-alpha.2, I tried my best to resolve those issues I mentioned above.
please let me know if you run into any issues on the libraries itself.

Still it will be very hard to use it because other libraries won't support elements running in new window
