### ISSUE TITLE
"dock-nav-more" are missing

### ISSUE THREAD

**Issue by Luigi600** [ticlo/rc-dock#56]
## Description

In small view, the element with the class "dock-nav-more" is not displayed (it does not even exist in the DOM tree). 
At the same time this is probably the reason for this bug:
![rc-dock-bug](https://user-images.githubusercontent.com/44069458/100524227-afe8a380-31b6-11eb-87c0-2d0c02ba10ad.gif)

## Expected Behavior

That a button is displayed with three dots, so you can still navigate to the tabs, just like in the example.
![rc-dock-expected-behavior](https://user-images.githubusercontent.com/44069458/100524283-14a3fe00-31b7-11eb-86bb-54c920b5d859.png)

## Environment / Tested With
```
react:16.13.1 & react:17.0.0
rc-dock:2.6.2, rc-dock:2.6.1, rc-dock:2.6.0, rc-dock:2.5.2 & rc-dock:2.0.0
```

## Minimal Example / Reproducion / Sandbox

I only copied the "basic" example, including the `less` files (renamed to scss).
[CodeSandbox](https://codesandbox.io/s/rc-dock-buttons-vqv2x?file=/src/App.tsx)

**Comment by rinick** [comment]
this is a known issue, have you tried 3.0.0-alpha.1
