### ISSUE TITLE
rc-dock drag-n-drop events doesn't work in Safari (12.1)

### ISSUE THREAD

**Issue by Likurg2010** [ticlo/rc-dock#6]
rc-dock just amazing, but it seems, drag-n-drop and resize events, connected with this lib, doesn't work in Safari. Is there any possible solutions or polyfills to eliminate this problem? 
P.S. This behavior you can see even on your page of examples (https://ticlo.github.io/rc-dock/examples/)

**Comment by rinick** [comment]
rc-dock use pointerdown event, right now you need to use #enable-pointer-events flag to turn on that feature for safari.
in the next build of safari this should be enabled by default.

**Comment by rinick** [comment]
there is a polyfill here, but I havn't tested it

https://github.com/jquery/PEP

**Comment by rinick** [comment]
Hi, I fixed this issue in latest build, and I it will be released to npm this weekend

**Comment by rinick** [comment]
touch support for ios is still pretty buggy, that part will require too much change. 
For now I will keep it as is and wait for Apple to implement those missing css for safari.

**Comment by Likurg2010** [comment]
Cool! Thanks a lot)
