### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by ahmadhaidarahmad** [ticlo/rc-dock#61]
Hi Im using rc-dock in my react application which is full of tabs and cards with load of real time data and api responses, because of the docking the application is being too much heavy and while moving the tab from when card to another it becomes too slow, and don't know the reason why.
If there is any guidance or help in debugging such cases in order to check the performance of the rc-dock.
Thank you in Advance
Regards

**Comment by rinick** [comment]
Hi @ahmadhaidarahmad 
is there a test case?

**Comment by ahmadhaidarahmad** [comment]
The test cases are on the live application whenever I get a Realtime data and start moving the tabs while updating data on my site the site becomes too much slow and the movement of tabs from one place to another becomes too slow , on the other hand when doing anything on the site without moving the tabs everything works properly and very smooth ( the lagging while moving the tabs shows that whenever a tab have a certain load of data it becomes too much heavy) 
if there is any scenario that you want me to do in order to generate a specific case I'm ready to do that 
Thank you again

**Comment by ahmadhaidarahmad** [comment]
Regarding version 3.0, I will check it

**Comment by ahmadhaidarahmad** [comment]
Please if you can set a link for the new features or fixes in version 3.0

**Comment by rinick** [comment]
> Please if you can set a link for the new features or fixes in version 3.0

https://github.com/ticlo/rc-dock/blob/master/HISTORY.md

**Comment by ahmadhaidarahmad** [comment]
Thank you a lot I will work on the version 3 and let you know
Regards
