### ISSUE TITLE
Moving/Maximising/Manipulating tabs causes re-render of inner components?

### ISSUE THREAD

**Issue by Triazic** [ticlo/rc-dock#63]
Hi, this library is very promising but there is a fatal flaw in its use for my app (or I'm just doing something wrong, which would be nice!).

I have a VERY expensive React component with lots of server logic etc. This cannot, ever, re-render. It is a pure component with no arguments. So in usual conditions, it has no reason to ever re-render. 

But when I maximise or move a tab, the component _does_ re-render :( 
I profiled and it says my component is being rendered for the first time.. meaning the tab which holds it has been destroyed and re-added from fresh.

Switching tabs works fine. Moving or maximising them seems to cause re-renders for their child components, even if those child components are pure/memoed etc. 

Please advise is this is something known, if I seem to be doing something wrong, or this is something fixable in source. Otherwise, this library is great.

**Comment by Triazic** [comment]
Could I use forwardRef to pass my component in from above and use ref.current in LayoutData?

**Comment by rinick** [comment]
have you tried tab cache?
https://ticlo.github.io/rc-dock/examples/#tab-cache

**Comment by rinick** [comment]
tab cache basically creates a react portal to avoid re-render when layout structure is changed

**Comment by Triazic** [comment]
I love you, man. This is great, works perfectly. 
I'll give you some money on Patreon
