### ISSUE TITLE
new-window incompatible with controlled-layout, and layout load/save

### ISSUE THREAD

**Issue by Triazic** [ticlo/rc-dock#64]
Heyo, 

I tried to implement the 'new-window' example in combination with with 'adv-save-layout' and 'controller-layout' examples.

'new-window' + controlled = windows don't pop up
'new window' + saveLayout = pop ups work, but saved pop out windows don't load

Totally understandable btw, I can imagine popout windows are diabolical to work with. I'll try to design around it.

**Comment by rinick** [comment]
I fixed it in 3.0.2
please let me know if it works for you

**Comment by rinick** [comment]
btw, the saved position of a popup window will be the position when it gets popup. 
this part is really tricky, especially when popup window is in another screen

**Comment by Triazic** [comment]
I won't be able to check this for a few weeks, I'll comment if it works OK

**Comment by vardhan03** [comment]
@Triazic, can you please let me know if you had found any workaround for this, thanks.

**Comment by Triazic** [comment]
From memory I got it to work, yes. I could control pop-up windows from controlled state and load/save from the 3.0.2 update rinick provided.

**Comment by vardhan03** [comment]
@Triazic, That's great! Can you please provide me a link to the code that you have done if possible, thanks :)
