### ISSUE TITLE
Allow new window popout with single button click

### ISSUE THREAD

**Issue by don1989** [ticlo/rc-dock#65]
Great to see that rc-dock now supports new window out of the box!

Currently we have an older version installed whereby we handle creating a new window ourselves from the content of the current floating tab. We do it with a single button click instead of a right-click and selecting New Window as per the example. 

Is it possible to also support this in rc-dock so that the popout can be initiated from a single button click on the panel?

Many thanks

**Comment by rinick** [comment]
you can do this yourself with panel-extra
just call dockMove() like this example:
https://ticlo.github.io/rc-dock/examples/#panel-extra
the third parameter should be "new-window"

**Comment by don1989** [comment]
OK great, thanks!
