### ISSUE TITLE
Building with Snowpack

### ISSUE THREAD

**Issue by jcuenod** [ticlo/rc-dock#68]
I can't get this to build with snowpack. Tbh, I've cycled through a number of failed attempts but the latest is this:

```
Unhandled Runtime Error

TypeError: Bowser$1.getParser is not a function
Source

http://localhost:8080/_snowpack/pkg/rc-dock.js [:15482:24]

BrowserPopupWindow<@http://localhost:8080/_snowpack/pkg/rc-dock.js:15482:24
createCommonjsModule@http://localhost:8080/_snowpack/pkg/common/index-fd450300.js:14:5
@http://localhost:8080/_snowpack/pkg/rc-dock.js:15439:46
```

I guess that I'm just using snowpack wrong b/c it uses modules instead of bundling. Any advice?

**Comment by rinick** [comment]
nope, I have no idea.

what if you build a blank project with only Bowser as the dependency? is it able to find Bowser.getParser?

**Comment by jcuenod** [comment]
Okay, it definitely appears related to the way snowpack is using es modules as opposed to commonjs.

I'm getting further by using

```
import DockLayout from "rc-dock/src/DockLayout.tsx"
```

But now I've got `String contains an invalid character` somewhere else...

**Comment by rinick** [comment]
did you use @snowpack/plugin-typescript ?

**Comment by jcuenod** [comment]
Did you get it working like that? I tried installing the ts plugin but to no avail. I'm pretty sure the problem is that rc-dock is a cjs module and snowpack wants it to be an esm.

**Comment by rinick** [comment]
@jcuenod 
could you check if this issue is resolved in version 3.0.3

**Comment by jcuenod** [comment]
It's getting further but still not resolved.
This is snowpack:

```
[snowpack] ! building dependencies...
[snowpack] /home/jcuenod/Programming/ttt/node_modules/rc-new-window/es/BrowserPopupWindow.js:2:23 'getParser' is not exported by 'node_modules/bowser/src/bowser.js'
```

In the browser, I get:

```
Unhandled Runtime Error
TypeError: undefined is not a function
http://localhost:8080/_snowpack/pkg/rc-dock.js:15432:26
```

That makes sense because somehow it's compiled to:

```js
const browser = undefined(window.navigator.userAgent)
```

`grep`ping "undefined" on that file produces quite a bit of output, though. So I guess that it really also depends on dependencies not being cjs modules either...

**Comment by jcuenod** [comment]
Just for reference, this is how I'm testing it: https://github.com/jcuenod/snowpack-rc-dock

**Comment by rinick** [comment]
the browser error is fixed in rc-new-window 0.1.6
but I still have this runtime error 
```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `DockTabs`.
```

**Comment by jcuenod** [comment]
Thanks!

**Comment by jcuenod** [comment]
I'm so sorry to do this but I just noticed that I am getting a pretty similar `bowser_1.default.getParser is not a function` when I do:

```js
import "rc-dock/dist/rc-dock.css"
```

**Comment by rinick** [comment]
> I'm so sorry to do this but I just noticed that I am getting a pretty similar `bowser_1.default.getParser is not a function` when I do:
> 
> ```js
> import "rc-dock/dist/rc-dock.css"
> ```

works for me, maybe it's just some bad cache?

**Comment by jcuenod** [comment]
Yup, my apologies it's working correctly.
I did have to add ` style={{ "height": "calc(100vh - 48px)" }}` to my `<Docklayout />`, though (the 48px is for a header). Without the height setting, it was hidden by a height of zero.
