### ISSUE TITLE
panelLock property allow floating of panels during dropMode 'edge'

### ISSUE THREAD

**Issue by Likurg2010** [ticlo/rc-dock#7]
Hi, i'm little bit confused with behavior of panelLock property during dropMode="edge". Is it normal situation, that in 'edge' mode panels can be dragged in floatbox when we are using panelLock?
P.S. In dropMode='default' panelLock works according to docs and disallow panels to be placed in floatbox

**Comment by rinick** [comment]
yes, that's a bug, I will fix it tonight
