### ISSUE TITLE
loadTab recieving only id

### ISSUE THREAD

**Issue by flieks** [ticlo/rc-dock#70]
Hi, 

great library, thanks alot. 

I have 1 issue using controlled layout.

![image](https://user-images.githubusercontent.com/5032389/109972445-9431f380-7cf7-11eb-8f1a-d738b65f1713.png)

In the dockbox i have 2 tabs. They have info like group and closable. But only the id of the tabs get serialized, which later in the serializer. loadBoxData it does LoadTab() where i have to return tabData but i only get the ID from the event...

The first time with initial state, i got the full object in loadTab, but it is after i hit the add button (in groupData.panelExtra), that only id's are given to loadTab()

Not sure this is a bug..

Greetings

**Comment by rinick** [comment]
no it's not a bug, usually your code should know better of what should be saved and what should not

you can just implement you own saveTab callback to save whatever you need
https://ticlo.github.io/rc-dock/examples/#adv-save-layout

**Comment by flieks** [comment]
true, well i am using the id's now to find the content (which is saved somewhere else with the ID)
Thanks
