### ISSUE TITLE
DockLayout.updateTab does not trigger onLayoutChange

### ISSUE THREAD

**Issue by don1989** [ticlo/rc-dock#71]
We have code in place whereby whenever a change is made to the layout, we save it to the cache/server.

Currently, when I make a change to a tab name using DockLayout.updateTab, I would expect that the callback assigned to onLayoutChange would have been called. However, currently it isn't. This means that we can't save the tab name change unless a different action is performed that triggers onLayoutChange.

As a workaround, I thought to explicitly call DockLayout.saveLayout just after we call DockLayout.updateTab. However the change to the tab name is not yet reflected in the layout at this point.

Note that we're also using the defaultLayout prop.

Please advise what I should do here or whether this can be changed.

Thanks!

**Comment by rinick** [comment]
I will fix that tomorrow

**Comment by rinick** [comment]
fixed in 3.0.5

**Comment by don1989** [comment]
Works! Thanks for the fast turnaround.
