### ISSUE TITLE
dockMove ts(2345)

### ISSUE THREAD

**Issue by sarasfive** [ticlo/rc-dock#75]
`dockMove` displays TypeScript error when passing `target` as `null`, though the documentation indicates: `when direction is 'remove' or 'front', target must be null`

From `DockLayout.d.ts`:

`dockMove(source: TabData | PanelData, target: string | TabData | PanelData | BoxData, direction: DropDirection): void;`

To ignore the error until addressed, prefix line e.g.:

```
// @ts-ignore
dockLayout.current?.dockMove(tab, null, 'remove')
```

**Comment by rinick** [comment]
@sarasfive thanks for the report,  I will fix that

**Comment by rinick** [comment]
fixed in the last commit
will be in the next release
