### ISSUE TITLE
Saving and reloading stateful layouts

### ISSUE THREAD

**Issue by jcuenod** [ticlo/rc-dock#76]
I have looked at the examples but they seem a bit contrived. I am wanting to allow users to dynamically add tabs (which could be any number of different "widgets"—each different react components) and rearrange them. I'd like to use something like localstorage to keep track of users' arrangements and reload the previous state when they return.

Is there an example of something like this? It seems difficult to rebuild a stateful layout that is totally dynamic.

**Comment by rinick** [comment]
did you define both saveTab and loadTab?
you will need to define what should be saved and how to load them

also if you need a callback every time user changes layout, you can check the controlled layout example
