### ISSUE TITLE
how to disable resizing of panel

### ISSUE THREAD

**Issue by sandeepsku** [ticlo/rc-dock#78]
my requirement is that i need to fix panel size and size should not increased by user interaction. i need to disable resizing.
there is minWidth and minHeight but they are not solving the purpose, as we dock panel that time size got changed. Appreciate any help.

**Comment by rinick** [comment]
think about this use case, Panel1 has fixed width of 300px, Panel2 has fixed width of 400px, now I need to dock Panel1 on top of Panel2, how do they look like? 

I think what you need is probably not a fully dockable layout
maybe your left side panel is fixed? why not just make them fixed? and only apply dockable layout in the right side?
and if you need some internal split(divider) panel feature in your fixed part of the layout, you can try rc-dock's raw divider box
https://ticlo.github.io/rc-dock/examples/#divider-box

**Comment by sandeepsku** [comment]
yes left side panel is fixed and only right side panel is dockable.
Please let me know the solution of below points- 
1- is there is any solution so i can stop resizing of panel?
2- when we drag panel we can dock it in all direction i.e. right , left, bottom and top, can we control this behavior?

**Comment by rinick** [comment]
you don't have to put everything in dock layout and request a new feature for it.
Why not just implement your own logic of the panel in the left, and use rc-dock in the right
