### ISSUE TITLE
How we can use setDropRect ? Is there any reference for the same ?

### ISSUE THREAD

**Issue by Divanshi27** [ticlo/rc-dock#79]
I wanted to restrict the docking to just two directions "right" and "bottom". Can I use setDropReact method to achieve this or can you suggest something else for this ?

**Comment by rinick** [comment]
how about doing it with CSS?
just hide these 2 classes:
 .dock-drop-left .dock-drop-top

**Comment by Divanshi27** [comment]
I have used dropMode="edge", if I add the following code in my css then it can be achieved. 
.dock-drop-edge {
  top: -500% !important;
  left: -500% !important;
}

Please suggest if it is fine to do in this manner or is there any better way to do this ?

**Comment by rinick** [comment]
it works for me in normal dropMode

just use 
```css
.dock-drop-left {
  display:none;
}
```

**Comment by Divanshi27** [comment]
ok, thanks for your help
