### ISSUE TITLE
content not loading, no active tab on first render

### ISSUE THREAD

**Issue by flieks** [ticlo/rc-dock#81]
Hi rinick,

The content of the tab does not want to load anymore
![image](https://user-images.githubusercontent.com/5032389/114202866-ea79fe00-9957-11eb-8409-c2d53b5421e9.png)

Ok, if i click on the tab it gets loaded/visible. But on first render of DockLayout it does not want to set the active tab even though it is set in the state:
![image](https://user-images.githubusercontent.com/5032389/114203183-35941100-9958-11eb-9cbd-cdcbfc50c17c.png)

It is strange, i did not update rc-dock and this was working before. I must have broke it but i cant see why because added lots of code

Greetings

**Comment by rinick** [comment]
@flieks  could you give a test case?

also id is supposed to be string, maybe your issue is caused by numeric id

**Comment by flieks** [comment]
Indeed, that was the issue :)
I tried making the string numeric but not the other way around. Thanks!
