### ISSUE TITLE
Is there a way to update a tab without making it active; uncontrolled layout

### ISSUE THREAD

**Issue by sarasfive** [ticlo/rc-dock#82]
For example, in a sidebar, there is a list of files. Selecting a file in the sidebar opens a tab or sets that tab active (if already open) with `updateTab`.

However, if the user wants to rename a file in the sidebar that is not selected, but has a tab open for that file, updating the tab with `updateTab` (e.g. to update the tab name) causes that tab to be active.

Is there a way to prevent this with an uncontrolled layout?

Cheers!

**Comment by rinick** [comment]
resolved in 3.0.10
