### ISSUE TITLE
Uncaught TypeError: Cannot add property parent, object is not extensible

### ISSUE THREAD

**Issue by flieks** [ticlo/rc-dock#83]
Hi,

I am constantly having this error now:
![image](https://user-images.githubusercontent.com/5032389/114792764-3e864780-9d89-11eb-8d1f-215df5ecc13b.png)

This works:
![image](https://user-images.githubusercontent.com/5032389/114793041-d08e5000-9d89-11eb-911d-a1ec7b7b4e38.png)

This does not work and gives the error
![image](https://user-images.githubusercontent.com/5032389/114793343-72ae3800-9d8a-11eb-958e-708d9d601562.png)

Greetings
Felix

**Comment by rinick** [comment]
@flieks is there a test case?
I'm not really sure what to do about those 2 screenshots

**Comment by flieks** [comment]
Sorry it was my bad. I was returning a component somewhere where i had to return an object.
