### ISSUE TITLE
Cannot add property floatbox, object is not extensible

### ISSUE THREAD

**Issue by markfried96** [ticlo/rc-dock#84]
Hi,

we're trying to include your package in our project. We want to use Redux with an immutable reducer (Immer JS) for storing and handling the layout state. Unfortunately we get the following error: 

```
TypeError: Cannot add property floatbox, object is not extensible

export function loadLayoutData(savedLayout, defaultLayout, loadTab, afterPanelLoaded) {
  90 |     if (!savedLayout.floatbox) {
> 91 |         savedLayout.floatbox = { mode: 'float', children: [], size: 0 };
  92 |     }
  93 |     if (!savedLayout.maxbox) {
  94 |         savedLayout.maxbox = { mode: 'maximize', children: [], size: 1 };
```

It looks like your library is trying to modify the layout... The problem is, that Immer JS is freezing the state object. 

Do you have an idea how to solve this problem?

**Comment by rinick** [comment]
I think I can clone the data instead of modifying the data.
could you create a repo for me to test this issue?

**Comment by markfried96** [comment]
Thanks for your quick response. Sure, I can create a demo repo. However I'm not really sure if just cloning the object is a good approach. We want to use your dock as a controlled layout. And as I understand the functionality correctly our code and your package should use the same reference of the layout object. And by copy you would always create a new reference. Do you now what I mean?

**Comment by rinick** [comment]
> Thanks for your quick response. Sure, I can create a demo repo. However I'm not really sure if just cloning the object is a good approach. We want to use your dock as a controlled layout. And as I understand the functionality correctly our code and your package should use the same reference of the layout object. And by copy you would always create a new reference. Do you now what I mean?

I don't think it matters, the savedLayout is just an input, and it's always different from the data structure used inside the controlled layout.

**Comment by rinick** [comment]
please check version 3.0.11
