### ISSUE TITLE
Headless usage

### ISSUE THREAD

**Issue by LoganDark** [ticlo/rc-dock#96]
Hello, if I want to make a version of this component with completely custom styling (i.e. support for light and dark modes) and HTML structure, how would I do that?

like, without using ant design at all (because the look does not fit my application at all)

**Comment by rinick** [comment]
There is no dark mode at the moment, but you can use your own css to adjust the styling.
just download https://github.com/ticlo/rc-dock/blob/master/dist/rc-dock.css and replace anything you need

the panel style example might also have something you need
https://ticlo.github.io/rc-dock/examples/#panel-style

**Comment by LoganDark** [comment]
I'm looking for something more like https://headlessui.dev/ , where you control not only the styling from the ground up, but also the HTML. Is that supported?

**Comment by rinick** [comment]
I don't think I will have time to support that natively.
Maybe you can use the source code instead of npm package, and apply your style directly
