### ISSUE TITLE
How to drag and drop a external component in layout as a tab? 

### ISSUE THREAD

**Issue by manojvicky** [ticlo/rc-dock#97]
Hi,
We are having a following requirement:
1. we are having a list of tab and they are in a separate component and we want to drag them into the layout.
2. we want to leverage same kind of drag-indicator functionality which is there whenever we drag any tab inside layout.

can i get some examples around it, or kind of idea how we can achieve that.

> external tab component

![image](https://user-images.githubusercontent.com/4014358/126026648-02369691-2282-4910-82e7-9b78a6a6470d.png)

> drag-indicator functionality

![image](https://user-images.githubusercontent.com/4014358/126026717-f40f2fb1-13c7-45b6-b5d9-9f56e6bbd730.png)

> drag-indicator we want on drag

![image](https://user-images.githubusercontent.com/4014358/126026797-07375051-6767-45d4-bf9a-274a819ba06b.png)

**Comment by rinick** [comment]
I will make a new example for that later

**Comment by manojvicky** [comment]
Thanks

**Comment by sagarpanda** [comment]
@manojvicky refer external component drag example [here](https://github.com/sagarpanda/rc-dock-external-dnd-demo/blob/master/src/DockDragExternal.tsx) and to play around [click here](https://sagarpanda.github.io/rc-dock-external-dnd-demo/).

**Comment by manojvicky** [comment]
@sagarpanda its working now, Thanks

**Comment by sagarpanda** [comment]
@rinick let me know if it is ok to send a pull request.

**Comment by rinick** [comment]
@manojvicky sorry for the delay,
I added the example.

and I will also change the internal error handling so you will no longer need a fake panel to do this in the future.

**Comment by rinick** [comment]
@sagarpanda 
thanks for the help!
