### ISSUE TITLE
Server side rendering: window is not defined

### ISSUE THREAD

**Issue by WeersProductions** [ticlo/rc-dock#99]
Hi!

This library looks awesome. Demos are very nice and intuitive (good idea on including the code there!).

I am picking up frontend development again, so I am not too familiar with it. I started with next.js and wanted to see whether I could make use of rc-dock. 

Using the example from the readme gives me the following error:
`ReferenceError: window is not defined
    at Object.<anonymous> (/workspaces/webserver/webserver/node_modules/rc-new-window/lib/BrowserPopupWindow.js:8:44)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/workspaces/webserver/webserver/node_modules/rc-new-window/lib/index.js:9:30)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)`

This is probably due NextJS rendering this on server-side (?). I was curious as to why the window is immediately required? I think I can dynamically load it and force it to be used on just the client-side, but I was wondering whether that's the way to go here, maybe you have an idea? Let me know if you need more information!

Thanks in advance!

**Comment by rinick** [comment]
it's trying to get user agent to predict browser's behavior
`const browser = Bowser.getParser(window.navigator.userAgent);`

I will fix that later

**Comment by WeersProductions** [comment]
Thanks! That would be awesome.

**Comment by rinick** [comment]
> Thanks! That would be awesome.

could you upgrade rc-new-window to 0.1.11, and see if that works for you?

**Comment by WeersProductions** [comment]
Thank you for the fast update!

That doesn't work yet, as the following line also makes use of window:
https://github.com/ticlo/rc-dock/blob/cf9c61a57e66c090543abcb71984c84632a6735b/src/WindowBox.tsx#L11 

Next to this, I noticed that the TypeScript in your commit looks good, but the generated JavaScript tries to evaluate whether window exists in the following way:
`const browser = window && bowser_1.default.getParser(window.navigator.userAgent);`
Looks like that already accesses `window` and throws an undefined-error. Not sure why the TypeScript does not compile to `typeof(window) !== 'undefined'`.

**Comment by rinick** [comment]
Ok, I will fix that

**Comment by rinick** [comment]
could you test rc-dock 3.0.18

**Comment by WeersProductions** [comment]
Thank you for your fast response again. Not sure why Typescript does not result in JS that works here. Strange.

In line https://github.com/ticlo/rc-new-window/blob/4a1a3bedc75591860fc4c366b14a6068ed3ccbc9/src/BrowserPopupWindow.ts#L42 , it is checked whether browser is null or not:
`exports.isSafari = (browser === null || browser === void 0 ? void 0 : browser.getBrowserName(true)) === 'safari';`
However, if browser window does not exist, browser is a boolean 🤔 . Adding the following print statement supports this:
`console.log(browser === null, typeof(browser), browser === void 0);`, which prints 'false boolean false'.

I'm therefore getting an error on that line, as it tries to execute 'getBrowserName'.

**Comment by WeersProductions** [comment]
This post gives some insight on why/how this is happening: https://dev.to/vvo/how-to-solve-window-is-not-defined-errors-in-react-and-next-js-5f97 
I am now loading this component dynamic (so on the client), because I saw a few more locations where 'window' is used  (e.g. resize events).

**Comment by rinick** [comment]
@WeersProductions  why would window be a problem if it's only used after class constructor is called? like resize event.

if that's not allowed, that basically means all code need to check if window exist before accessing it. and that applies to all your dependencies.

**Comment by WeersProductions** [comment]
Sorry for not responding sooner. I will take a closer look at this in the coming weeks. Thanks again for all your support! Will let you know.
